### ISSUE TITLE
Modeling and Training  of EMK/NMK Learner

### ISSUE THREAD

**Issue by WoodSugar** [panzheyi/ST-MetaNet#4]
I have read the source code and the idea of EMK/NMK learner is interesting.

But I can't find them in the source data. It seems that the training process of both two learners is not provided in the source, and the training results have been saved in the "FEATURE.h5" file. 

**Would you provide the training strategy of the embedding vectors with edge/node meta knowledge if it is convenient for you?**

**Comment by panzheyi** [comment]
Hi, both the EMK/NMK learners are basic fully connected layers.

The NMK learner is defined as `geo_encoder` in  `flow-prediction/src/model/seq2seq.py` line 202.
The EMK learner is defined as `w_mlp` in `flow-prediction/src/model/graph.py` line 127. 

BTW, `FEATURE.h5` contains the input features of nodes, such as the number of POIs and roads in each grid.
These features are not the embedding vectors.
These data are fed into the NMK learner, and the output is node meta knowledge (Please refer to `flow-prediction/src/model/seq2seq.py` line 231). You can use `meta_knowledge()` function in `flow-prediction/src/model/seq2seq.py` to get the embeddings.

**Comment by WoodSugar** [comment]
Thank you very much! I have found it
