### ISSUE TITLE
Regarding update function in MetaGat

### ISSUE THREAD

**Issue by cmcuza** [panzheyi/ST-MetaNet#7]
Hi, 

Thank you for sharing the code.

In the article, you said that the new state h(i) of MetaGAT is calculated by a linear combination of the previous hidden state and the new state calculated with the attention mechanism. In other words:

![Screenshot from 2020-11-10 17-36-12](https://user-images.githubusercontent.com/38991005/98702934-488bc080-237b-11eb-9d27-418576132a07.png)

However, in the code, I can only find the right side of the equation in the function **msg_reduce**. Is this enough or maybe a **msg_update** function should be added to apply the previous formula? 

Thank you in advance,
Best regards.

**Comment by panzheyi** [comment]
Hi, the implementation of this code is slightly different from the paper.

The implementation is:

<a href="https://www.codecogs.com/eqnedit.php?latex=\bar{h}^{(i)}&space;=&space;\bar{h}^{(i)}&plus;\lambda^{(i)}\sigma(\sum&space;a^{(ij)}h^{(j)})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\bar{h}^{(i)}&space;=&space;\bar{h}^{(i)}&plus;\lambda^{(i)}\sigma(\sum&space;a^{(ij)}h^{(j)})" title="\bar{h}^{(i)} = \bar{h}^{(i)}+\lambda^{(i)}\sigma(\sum a^{(ij)}h^{(j)})" /></a>  

(pls refer to line 128 in `flow-prediction/src/model/seq2seq.py` and msg_reduce).

The only difference is the scale of the hidden states. And such a difference can be tackled by neural networks.

Anyway, both implementations are available to reproduce the reported results in our paper.

**Comment by cmcuza** [comment]
Hi, thank you for the reply :+1:
